# Generated by Django 6.1.1 on 2026-09-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('ACTION', 'Acción'), ('ADVENTURE', 'Aventura'), ('RPG', 'Rol'), ('SHOOTER', 'Disparos'), ('PUZZLE', 'Puzle'), ('SIMULATION', 'Simulación'), ('SPORTS', 'Deportes'), ('STRATEGY', 'Estrategia')], max_length=20)),
                ('plataforma', models.CharField(choices=[('PC', 'PC'), ('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('XBOX_ONE', 'Xbox One'), ('XBOX_SERIES_X', 'Xbox Series X'), ('NINTENDO_SWITCH', 'Nintendo Switch'), ('MOBILE', 'Móvil'), ('OTHER', 'Otro')], max_length=20)),
                ('ano_lanzamiento', models.DateTimeField()),
                ('creacion_objeto', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
